### ISSUE TITLE
Migrate to `libgz-math7` and `libsdformat14`

### ISSUE THREAD

**Issue by azeey** [ros/sdformat_urdf#21]
Currently `sdformat_urdf` uses an ignition package `libignition-math6` and an old version of sdformat `libsdformat12`. It would be great if the next version of ROS can use `libgz-math7` and `libsdformat14`.

**Comment by sloretz** [comment]
[ROS Rolling and Iron target Fortress](https://www.ros.org/reps/rep-2000.html#iron-irwini-may-2023-november-2024). It looks like [math 6 and sdformat 12 are the Fortress versions](https://gazebosim.org/docs/harmonic/release-features#fortress).

I'd recommend watching for PRs to REP 2000 in https://github.com/ros-infrastructure/rep in November 2023 for ROS Jazzy and recommending the next Gazebo version to target there.

@clalancette What's Marco's github username? Just want to ping him as an FYI

**Comment by clalancette** [comment]
> [ROS Rolling and Iron target Fortress](https://www.ros.org/reps/rep-2000.html#iron-irwini-may-2023-november-2024). It looks like [math 6 and sdformat 12 are the Fortress versions](https://gazebosim.org/docs/harmonic/release-features#fortress).
> 
> I'd recommend watching for PRs to REP 2000 in https://github.com/ros-infrastructure/rep in November 2023 for ROS Jazzy and recommending the next Gazebo version to target there.
> 
> @clalancette What's Marco's github username? Just want to ping him as an FYI

It's @marcoag

**Comment by azeey** [comment]
Thanks @sloretz. I've subscribed to that repo and will followup in November.

**Comment by azeey** [comment]
Fixed by https://github.com/ros/sdformat_urdf/pull/28
