### ISSUE TITLE
Issues resolving mesh uri with `model://`

### ISSUE THREAD

**Issue by Yadunund** [ros/sdformat_urdf#25]
I'm trying to migrate the use of `udrf`s to `sdf`s for better native support in gz. One big concern is passing the `sdf` file to a `robot_state_publisher` node which typically takes in a `urdf`. Thanks to `sdformat_urdf`, the node is able to parse + convert the `sdf` to a `urdf` and publish the robot descritpion as a string.

An issue arises when mesh `uri`s in the `sdf` are specified as `model://<model_name>/<path_to_mesh>`. While `gz` can resolve such paths, `rviz` which relies on `resource_retriever` cannot. As a result, the `RobotModel` cannot be visualized in rviz. The same holds true for `sdf` `uri`s that have relative paths.

Conversely, if the `uri` in the `sdf` is specified as `package://<package_name>/<path_to_mesh>`, the `RobotModel` can be visualized in `rviz` but the `sdf` will not be loaded in `gz`.

One way to resolve this is to have `sdformat_url` resolve `uri`s with `model://` to absolute paths and construct the `urdf` `uri` as `file://<absolute_path_to_mesh>`. Likely requires `sdformat_urdf` to parse `GZ_RESOURCE_PATH`.

Any other thoughts on how to overcome this issue?

**Comment by gavanderhoorn** [comment]
#20?

**Comment by Yadunund** [comment]
> #20?

Ah didn't notice that!

I'll leave this ticket open so that the maintainers can link it to that PR.
