### ISSUE TITLE
Foxy release?

### ISSUE THREAD

**Issue by chapulina** [ros/sdformat_urdf#3]
I see that this package is available on [Galactic and Rolling](https://index.ros.org/p/sdformat_urdf/github-ros-sdformat_urdf/#galactic). Would it be possible to release it for Foxy as well?

**Comment by sloretz** [comment]
IIRC I don't think it can be released into Foxy. It requires this PR to the `urdf` package: https://github.com/ros2/urdf/pull/13

**Comment by chapulina** [comment]
Aw gotcha :confused:
