### ISSUE TITLE
sdformat_urdf in ROS 2 Rolling has not been released on Ubuntu Jammy

### ISSUE THREAD

**Issue by nuclearsandwich** [ros/sdformat_urdf#4]
The ROS 2 Rolling Ridley distribution recently [migrated to Ubuntu 22.04 Jammy](https://github.com/ros/rosdistro/pull/32036) using the rosdistro migration tool.

This repository is one which failed to bloom during the migration because the `sdformat` dependency is not yet available in Ubuntu Jammy. Once the Jammy repositories and the rosdep database are updated it should be possible to release this repository in Rolling again by running bloom normally.

Packages which are not released in Rolling may not be automatically added to future stable ROS 2 distributions.

**Comment by chapulina** [comment]
Humble and Rolling are passing CI, so this just needs to be bloomed 🌷  Let me know if I can help with anything, @sloretz 

* https://github.com/ros/sdformat_urdf/pull/12

**Comment by sloretz** [comment]
I released to Rolling and Humble in https://github.com/ros/rosdistro/pull/33651 and https://github.com/ros/rosdistro/pull/33652

`sdformat12` doesn't seem to be available on RHEL or [Debian Bullseye](https://github.com/gazebo-tooling/release-tools/issues/596#issuecomment-1162475481), so I skipped those platforms.
